version: "3"

volumes:
  mongo_data:

services:
  api:
    build: ./api
    container_name: todo_api
    command: uvicorn main:app --host ${api_host} --port ${api_port} --reload
    volumes:
      - ./api/src:/src
    ports:
      - "${api_port}:${api_port}"
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGODB_USER: ${MONGO_INITDB_ROOT_USERNAME}
      MONGODB_PASS: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    links:
      - 'mongodb:mongo'
    restart: always
    ports:
      - ${MONGO_EXPRESS_PORT}:${MONGO_EXPRESS_PORT}
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}