version: "3"

volumes:
  mongo_data:

services:
  api:
    build: ./api
    container_name: todo_api
    command: uvicorn main:app --host ${api_host} --port ${api_port} --reload
    volumes:
      - ./api/src:/src
    ports:
      - "${api_port}:${api_port}"
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${DB_PORT}:${DB_PORT}"
